Python/Tema12/Ejercicio1/cine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('directores.urls')),

]

Python/Tema12/Ejercicio1/directores/urls.py
from django.urls import path
from.import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('director/<pk>', views.DirectorView.as_view(), name='datail_director'),
    path('film/<pk>', views.FilmView.as_view(), name='detail_film'),
]

Python/Tema12/Ejercicio1/directores/models.py
from django.db import models



class Genre(models.Model):
    genreFilm=models.CharField(max_length=64,help_text='Introduzca el género de la pelicula.')

    def __str__(self):
        return self.genreFilm
    
class Film(models.Model):
    title=models.CharField(max_length=64,help_text='Introduzca el nombre de la película.')
    director=models.ForeignKey('Director',on_delete=models.SET_NULL, null=True)
    genre=models.ManyToManyField('Genre',help_text='Seleccione uno o varios géneros.')
    year=models.IntegerField(help_text='Introduzca el año que se estrenó')
    duration=models.IntegerField(help_text='Introduzca los minutos que dura la película')
    synopsis=models.TextField(max_length=1000,help_text='Sinopsis de la película.')

    def __str__(self):
        return self.title

class Director(models.Model):
    name=models.CharField(max_length=64,help_text='Introduzca el nombre del director.')
    biography=models.TextField(max_length=1000,help_text='Introduzca la biografía del director.')
       
    def __str__(self):
        return self.name

Python/Tema12/Ejercicio1/directores/views.py
from django.views import generic
from .models import Director, Film

class IndexView(generic.ListView):
    template_name = 'index.html'
    model = Director

class DirectorView(generic.DetailView):
    template_name = 'director.html'
    model = Director
    
    
    """
    def get_context_data(self, **kwargs):
        context=super(FilmView,self).get_context_data(**kwargs)
        context['genero']=Film.objects.all()
        return context
    def get_context_data(self, **kwargs):
        context=super(DirectorView,self).get_context_data(**kwargs)
        context['film_list']=Film.objects.all
        return super().get_context_data(**kwargs)
    context_object_name=Director
    """

class FilmView(generic.DetailView):
    template_name = 'film.html'
    model = Film
    
    def get_context_data(self, **kwargs):
        context=super(FilmView,self).get_context_data(**kwargs)
        context['genero']=Film.objects.all()
        return context
    


Python/Tema12/Ejercicio1/directores/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>{% block title %}Directores de cine{% endblock %}</title>
</head>

<body>
    <header>
        <h1>{% block header-title %}Directores{% endblock %}</h1>
    </header>
    <main>{% block content %}{% endblock %}</main>
</body>
</html>

Python/Tema12/Ejercicio1/directores/templates/director.html
{% extends "base.html" %}

{% block title %}Director - {{ director }}{% endblock %}

{% block header-title %}{{ director }}{% endblock %}

{% block content %}
<h4>Biografía</h4>
<p>{{ director.biography}}</p>

<h4>Peliculas:</h4>
<table>
    {% for film in director.film_set.all %}
     
        <tr>
        <td onclick="window.location.href='/film/{{film.id}}'">
            <h5>{{ film }}</h5>
        </td>
        </tr>

    {% empty %}
        <td>No hay peliculas aún</td>
    {% endfor %}
    
</table>
{% endblock %}

Python/Tema12/Ejercicio1/directores/templates/film.html
{% extends "base.html" %}

{% block title %}Pelicula - {{ film.title }}{% endblock %}

{% block header-title %}{{ film }}{% endblock %}

{% block content %}
<p><b>Director/a: </b>{{ film.director}}</p>
<p><b>Año: </b>{{ film.year}}</p>
<p><b>Duración: </b>{{ film.duration}} minutos</p>
<h4>Sinopsis</h4>
<p>{{ film.synopsis}}</p>
{% endblock %}

Python/Tema12/Ejercicio1/directores/templates/index.html
{% extends "base.html" %}

{% block title %}Directores{% endblock %}


{% block content %}
<table>
    
    {% for director in object_list %}
        <tr>
        <td onclick="window.location.href='director/{{director.id}}'">
            <h4><span class="name_director">{{ director }}</span></h4>
        
        </td>
        </tr>
              
    {% endfor %}
    
</table>

{% endblock %}